;FIXPOI.MAC
;Makros fr Fixpunktoperationen
;Marius Greuel '95

;1/16 * 1/16 Multiplikation
;> EAX = Faktor 1
;  #1 = Faktor 2
;< EAX = Produkt
;  EDX zerst”rt
MUL16	macro Faktor
	imul dword ptr Faktor
	xchg ax,dx
	ror eax,16
	endm

;1/16 / 1/16 Division
;> EAX = Dividend
;  #1 = Divisor
;< EAX = Quotient
;  EDX zerst”rt
Div16	macro Divisor
	cdq
	ror eax,16
	xchg ax,dx
	xor ax,ax
	idiv dword ptr Divisor
	endm

;1/30 * 1/30 Multiplikation
;> EAX = Faktor 1
;  #1 = Faktor 2
;< EDX = Produkt
;  EAX zerst”rt
Mul30	macro Faktor
	imul dword ptr Faktor
	shl eax,1
	rcl edx,1
	shl eax,1
	rcl edx,1
	endm

;1/30 / 1/30 Division
;> EDX = Dividend
;  #1 = Divisor
;< EAX = Quotient
;  EDX zerst”rt
Div30	macro Divisor
	sub eax,eax
	sar edx,1
	rcr eax,1
	sar edx,1
	rcr eax,1
	idiv dword ptr Divisor
	endm

